server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: kairos

    autoconfigure:
      exclude:
        - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
        - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
        - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

logging:
  level:
    ru.kairos: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

app:
  name: "Kairos"
  version: "1.0.0"
  description: "Сервис для поиска и бронирования мест для отдыха"
